allowBuilds:
  core-js: set this to true or false
  esbuild: set this to true or false
  jsonpath: set this to true or false
  msw: true
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@0.2.6
  vitest: 4.1.10
  vite-plus: 0.2.6
overrides:
  vite: 'catalog:'
  vitest: 'catalog:'
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: '*'
    vitest: '*'
