/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppMediaRouteImport } from './routes/app/media'
import { Route as AppWorkspaceRouteImport } from './routes/app/workspace'
import { Route as AppWorkspaceIndexRouteImport } from './routes/app/workspace/index'
import { Route as AppWorkspaceVideoIdRouteImport } from './routes/app/workspace/$videoId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppMediaRoute = AppMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkspaceRoute = AppWorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkspaceIndexRoute = AppWorkspaceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppWorkspaceRoute,
} as any)
const AppWorkspaceVideoIdRoute = AppWorkspaceVideoIdRouteImport.update({
  id: '/$videoId',
  path: '/$videoId',
  getParentRoute: () => AppWorkspaceRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/media': typeof AppMediaRoute
  '/app/workspace': typeof AppWorkspaceRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/app/workspace/$videoId': typeof AppWorkspaceVideoIdRoute
  '/app/workspace/': typeof AppWorkspaceIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/media': typeof AppMediaRoute
  '/app': typeof AppIndexRoute
  '/app/workspace/$videoId': typeof AppWorkspaceVideoIdRoute
  '/app/workspace': typeof AppWorkspaceIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/media': typeof AppMediaRoute
  '/app/workspace': typeof AppWorkspaceRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/app/workspace/$videoId': typeof AppWorkspaceVideoIdRoute
  '/app/workspace/': typeof AppWorkspaceIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/media'
    | '/app/workspace'
    | '/app/'
    | '/app/workspace/$videoId'
    | '/app/workspace/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/app/media' | '/app' | '/app/workspace/$videoId' | '/app/workspace'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/media'
    | '/app/workspace'
    | '/app/'
    | '/app/workspace/$videoId'
    | '/app/workspace/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/media': {
      id: '/app/media'
      path: '/media'
      fullPath: '/app/media'
      preLoaderRoute: typeof AppMediaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/workspace': {
      id: '/app/workspace'
      path: '/workspace'
      fullPath: '/app/workspace'
      preLoaderRoute: typeof AppWorkspaceRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/workspace/': {
      id: '/app/workspace/'
      path: '/'
      fullPath: '/app/workspace/'
      preLoaderRoute: typeof AppWorkspaceIndexRouteImport
      parentRoute: typeof AppWorkspaceRoute
    }
    '/app/workspace/$videoId': {
      id: '/app/workspace/$videoId'
      path: '/$videoId'
      fullPath: '/app/workspace/$videoId'
      preLoaderRoute: typeof AppWorkspaceVideoIdRouteImport
      parentRoute: typeof AppWorkspaceRoute
    }
  }
}

interface AppWorkspaceRouteChildren {
  AppWorkspaceVideoIdRoute: typeof AppWorkspaceVideoIdRoute
  AppWorkspaceIndexRoute: typeof AppWorkspaceIndexRoute
}

const AppWorkspaceRouteChildren: AppWorkspaceRouteChildren = {
  AppWorkspaceVideoIdRoute: AppWorkspaceVideoIdRoute,
  AppWorkspaceIndexRoute: AppWorkspaceIndexRoute,
}

const AppWorkspaceRouteWithChildren = AppWorkspaceRoute._addFileChildren(
  AppWorkspaceRouteChildren,
)

interface AppRouteChildren {
  AppMediaRoute: typeof AppMediaRoute
  AppWorkspaceRoute: typeof AppWorkspaceRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppMediaRoute: AppMediaRoute,
  AppWorkspaceRoute: AppWorkspaceRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
