// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { YoutubeSearchListData, YoutubeSearchListResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Retrieves a list of search resources
 */
export const youtubeSearchList = <ThrowOnError extends boolean = false>(options: Options<YoutubeSearchListData, ThrowOnError>): RequestResult<YoutubeSearchListResponses, unknown, ThrowOnError> => (options.client ?? client).get<YoutubeSearchListResponses, unknown, ThrowOnError>({
    security: [{
            key: 'Oauth2',
            scheme: 'bearer',
            type: 'http'
        }, {
            key: 'Oauth2c',
            scheme: 'bearer',
            type: 'http'
        }],
    url: '/youtube/v3/search',
    ...options
});
